name: lahzet_zikry
description: "دفتر إلكتروني عربي لتسجيل الذكريات والمذكرات اليومية"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  local_auth: ^2.3.0
  shared_preferences: ^2.2.2
  fluttertoast: ^9.0.0
  intl: ^0.20.2
  image_picker: ^1.1.1
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.0
  video_player: ^2.8.3
  just_audio: ^0.9.38
  path_provider: ^2.1.4
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/appIcon.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
